---
title: "PrestoGP practice example with given data"
output: html_document
---


```{r setup, message=FALSE, warning=FALSE}
.libPaths("/usr/local/lib/R/site-library")
library(PrestoGP)
library(ggplot2)
set.seed(2025)
```


```{r load-data}
data(soil, package = "PrestoGP")
soil <- soil[!is.na(soil[,5]),]
y <- soil[,4]             # moisture content
X <- as.matrix(soil[,5:9])
locs <- as.matrix(soil[,1:2])
str(list(y=y, X=dim(X), locs=dim(locs)))
```

```{r fit-model}
soil.vm <- new("VecchiaModel", n_neighbors = 10)
soil.vm <- prestogp_fit(soil.vm, y, X, locs)
soil.vm
```

```{r impute-missing-y}
miss <- sample(1:nrow(soil), 20)
y.miss <- y
y.miss[miss] <- NA
soil.vm2 <- new("VecchiaModel", n_neighbors = 10)
soil.vm2 <- prestogp_fit(soil.vm2, y.miss, X, locs, impute.y = TRUE)
soil.vm2
```


```{r Impute-y-missing-due-to-limit-of-detection}
soil.lod <- quantile(y, 0.1)
y.lod <- y
y.lod[y.lod <= soil.lod] <- NA
soil.vm3 <- new("VecchiaModel", n_neighbors = 10)
soil.vm3 <- prestogp_fit(soil.vm3, y.lod, X, locs, impute.y = TRUE, lod.upper = soil.lod)
soil.vm3

```


```{r full-model}
soil.fm <- new("FullModel")
soil.fm <- prestogp_fit(soil.fm, y, X, locs)
soil.fm
```


```{r multivariate-model}
ym <- list(soil[,5], soil[,7])                 # two nitrogen concentrations
Xm <- list(); Xm[[1]] <- Xm[[2]] <- as.matrix(soil[,c(4,6,8,9)])
locsm <- list(); locsm[[1]] <- locsm[[2]] <- locs

soil.mvm <- new("MultivariateVecchiaModel", n_neighbors = 10)
soil.mvm <- prestogp_fit(soil.mvm, ym, Xm, locsm)
soil.mvm
```


```{r space-elevation-model}

library(geoR)
data(soil250, package = "geoR")
y2 <- soil250[,7]                            # pH
X2 <- as.matrix(soil250[,c(4:6,8:22)])
locs2 <- as.matrix(soil250[,1:3])            # x, y, elevation

soil.vm.elev <- new("VecchiaModel", n_neighbors = 10)
soil.vm.elev <- prestogp_fit(soil.vm.elev, y2, X2, locs2, scaling = c(1,1,2))
soil.vm.elev


```


```{r plot}
df_plot <- data.frame(y = y, x = X[,1])
ggplot(df_plot, aes(x, y)) + geom_point(alpha = 0.5) + labs(x="X1", y="Moisture")

```